**Exercise 1.1**

1) Open up a new Jupyter notebook  
2) Download a few MTA turnstile data files  
3) Open up a file, use csv reader to read it, make a python dict where there is a key for each (C/A, UNIT, SCP, STATION). These are the first four columns. The value for this key should be a list of lists. Each list in the list is the rest of the columns in a row.

In [3]:
# Setup -- I will use Pandas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from IPython.display import Image

%matplotlib inline

pd.set_option('display.max_rows', 100)


# I chose the last four weeks, labeled from 1-4 from furthest back to most recent
week1 = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_160827.txt')
week2 = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_160903.txt')
week3 = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_160910.txt')
week4 = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_160917.txt')

weeks = [week1, week2, week3, week4]

month = pd.concat(weeks)


#Create one column from the first 4
month['LOCATION'] = month['C/A'] + "," + month['UNIT'] + "," + month['SCP'] + "," + month['STATION']

month = month[month['C/A'] != 'TRAM1']
month = month[month['C/A'] != 'TRAM2']

# Delete superfluous columns
month = month.drop(['C/A', 'UNIT', 'SCP', 'STATION'], axis=1, errors ="ignore")

# Reorder columns so LOCATION is at the front
cols = month.columns.tolist()
cols = cols[-1:] + cols[:-1]
month = month[cols]

month.info()
month.head(50)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 770831 entries, 0 to 192457
Data columns (total 8 columns):
LOCATION                                                                770831 non-null object
LINENAME                                                                770831 non-null object
DIVISION                                                                770831 non-null object
DATE                                                                    770831 non-null object
TIME                                                                    770831 non-null object
DESC                                                                    770831 non-null object
ENTRIES                                                                 770831 non-null int64
EXITS                                                                   770831 non-null int64
dtypes: int64(2), object(6)
memory usage: 52.9+ MB

,LOCATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/20/2016,00:00:00,REGULAR,5790246,1963095
1,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/20/2016,04:00:00,REGULAR,5790275,1963101
2,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/20/2016,08:00:00,REGULAR,5790284,1963123
3,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/20/2016,12:00:00,REGULAR,5790377,1963178
4,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/20/2016,16:00:00,REGULAR,5790605,1963230
5,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/20/2016,20:00:00,REGULAR,5790926,1963287
6,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/21/2016,00:00:00,REGULAR,5791095,1963314
7,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/21/2016,04:00:00,REGULAR,5791132,1963319
8,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/21/2016,08:00:00,REGULAR,5791141,1963334
9,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/21/2016,12:00:00,REGULAR,5791217,1963404
10,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/21/2016,16:00:00,REGULAR,5791385,1963451
11,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/21/2016,20:00:00,REGULAR,5791648,1963491
12,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/22/2016,00:00:00,REGULAR,5791766,1963515
13,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/22/2016,04:00:00,REGULAR,5791782,1963519
14,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/22/2016,08:00:00,REGULAR,5791829,1963611
15,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/22/2016,12:00:00,REGULAR,5792007,1963850
16,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/22/2016,16:00:00,REGULAR,5792315,1963919
17,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/22/2016,20:00:00,REGULAR,5793152,1963974
18,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/23/2016,00:00:00,REGULAR,5793399,1964002
19,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/23/2016,04:00:00,REGULAR,5793422,1964007
20,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/23/2016,08:00:00,REGULAR,5793475,1964117
21,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/23/2016,12:00:00,REGULAR,5793656,1964344
22,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/23/2016,16:00:00,REGULAR,5793961,1964421
23,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/23/2016,20:00:00,REGULAR,5794827,1964470
24,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/24/2016,00:00:00,REGULAR,5795047,1964497
25,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/24/2016,04:00:00,REGULAR,5795068,1964501
26,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/24/2016,08:00:00,REGULAR,5795107,1964589
27,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/24/2016,12:00:00,REGULAR,5795291,1964847
28,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/24/2016,16:00:00,REGULAR,5795619,1964931
29,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/24/2016,20:00:00,REGULAR,5796445,1964995
30,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/25/2016,00:00:00,REGULAR,5796665,1965027
31,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/25/2016,04:00:00,REGULAR,5796672,1965028
32,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/25/2016,08:00:00,REGULAR,5796706,1965132
33,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/25/2016,12:00:00,REGULAR,5796863,1965391
34,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/25/2016,16:00:00,REGULAR,5797068,1965467
35,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/25/2016,20:00:00,REGULAR,5797735,1965533
36,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/26/2016,00:00:00,REGULAR,5797976,1965560
37,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/26/2016,04:00:00,REGULAR,5798002,1965564
38,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/26/2016,08:00:00,REGULAR,5798027,1965667
39,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/26/2016,12:00:00,REGULAR,5798179,1965888
40,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/26/2016,16:00:00,REGULAR,5798549,1965964
41,"A002,R051,02-00-00,59 ST",NQR456,BMT,08/26/2016,20:00:00,REGULAR,5799243,1966014
42,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/20/2016,00:00:00,REGULAR,5321520,1167376
43,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/20/2016,04:00:00,REGULAR,5321547,1167377
44,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/20/2016,08:00:00,REGULAR,5321570,1167414
45,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/20/2016,12:00:00,REGULAR,5321661,1167495
46,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/20/2016,16:00:00,REGULAR,5321862,1167545
47,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/20/2016,20:00:00,REGULAR,5322140,1167581
48,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/21/2016,00:00:00,REGULAR,5322299,1167597
49,"A002,R051,02-00-01,59 ST",NQR456,BMT,08/21/2016,04:00:00,REGULAR,5322326,1167597

**Exercise 1.2**

Let's turn this into a time series. For each key (basically the control area, unit, device address and station of a specific turnstile), have a list again, but let the list be comprised of just the point in time and the count of entries. 

This basically means keeping only the date, time, and entries fields in each list. You can convert the date and time into datetime objects -- That is a python class that represents a point in time. You can combine the date and time fields into a string and use the dateutil module to convert it into a datetime object. For an example check this StackOverflow question.

In [4]:
# Merge date and time into a single column and then transform values into datetime objects
month['DATE/TIME'] = month['DATE'] + " " + month['TIME']
month['DATE/TIME'] = pd.to_datetime(month['DATE/TIME'], infer_datetime_format=True)

# Eliminate superfluous columns & reorder
month = month[['LOCATION', 'DATE/TIME', 'ENTRIES']]

month.info()
month.head(20)

# NOTE: I first tried to drop superfluous columns with the line below.  What happened was very strange: it dropped all
# but 'EXITS', and I couldn't figure out why it wouldn't drop that one.
#month = month.drop(['LINENAME', 'DIVISION', 'DESC', 'EXITS'], axis=1, errors="ignore")

<class 'pandas.core.frame.DataFrame'>
Int64Index: 770831 entries, 0 to 192457
Data columns (total 3 columns):
LOCATION     770831 non-null object
DATE/TIME    770831 non-null datetime64[ns]
ENTRIES      770831 non-null int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 23.5+ MB

                    LOCATION           DATE/TIME  ENTRIES
0   A002,R051,02-00-00,59 ST 2016-08-20 00:00:00  5790246
1   A002,R051,02-00-00,59 ST 2016-08-20 04:00:00  5790275
2   A002,R051,02-00-00,59 ST 2016-08-20 08:00:00  5790284
3   A002,R051,02-00-00,59 ST 2016-08-20 12:00:00  5790377
4   A002,R051,02-00-00,59 ST 2016-08-20 16:00:00  5790605
5   A002,R051,02-00-00,59 ST 2016-08-20 20:00:00  5790926
6   A002,R051,02-00-00,59 ST 2016-08-21 00:00:00  5791095
7   A002,R051,02-00-00,59 ST 2016-08-21 04:00:00  5791132
8   A002,R051,02-00-00,59 ST 2016-08-21 08:00:00  5791141
9   A002,R051,02-00-00,59 ST 2016-08-21 12:00:00  5791217
10  A002,R051,02-00-00,59 ST 2016-08-21 16:00:00  5791385
11  A002,R051,02-00-00,59 ST 2016-08-21 20:00:00  5791648
12  A002,R051,02-00-00,59 ST 2016-08-22 00:00:00  5791766
13  A002,R051,02-00-00,59 ST 2016-08-22 04:00:00  5791782
14  A002,R051,02-00-00,59 ST 2016-08-22 08:00:00  5791829
15  A002,R051,02-00-00,59 ST 2016-08-22 12:00:00  5792007
16  A002,R051,02-00-00,59 ST 2016-08-22 16:00:00  5792315
17  A002,R051,02-00-00,59 ST 2016-08-22 20:00:00  5793152
18  A002,R051,02-00-00,59 ST 2016-08-23 00:00:00  5793399
19  A002,R051,02-00-00,59 ST 2016-08-23 04:00:00  5793422

In [6]:
# Sort the data by LOCATION AND DATE/TIME, and reindex
month = month.sort_values(['LOCATION', 'DATE/TIME'])

month = month.reset_index()
month = month.drop('index', axis = 1)

month

                                LOCATION           DATE/TIME  ENTRIES
0               A002,R051,02-00-00,59 ST 2016-08-20 00:00:00  5790246
1               A002,R051,02-00-00,59 ST 2016-08-20 04:00:00  5790275
2               A002,R051,02-00-00,59 ST 2016-08-20 08:00:00  5790284
3               A002,R051,02-00-00,59 ST 2016-08-20 12:00:00  5790377
4               A002,R051,02-00-00,59 ST 2016-08-20 16:00:00  5790605
5               A002,R051,02-00-00,59 ST 2016-08-20 20:00:00  5790926
6               A002,R051,02-00-00,59 ST 2016-08-21 00:00:00  5791095
7               A002,R051,02-00-00,59 ST 2016-08-21 04:00:00  5791132
8               A002,R051,02-00-00,59 ST 2016-08-21 08:00:00  5791141
9               A002,R051,02-00-00,59 ST 2016-08-21 12:00:00  5791217
10              A002,R051,02-00-00,59 ST 2016-08-21 16:00:00  5791385
11              A002,R051,02-00-00,59 ST 2016-08-21 20:00:00  5791648
12              A002,R051,02-00-00,59 ST 2016-08-22 00:00:00  5791766
13              A002,R051,02-00-00,59 ST 2016-08-22 04:00:00  5791782
14              A002,R051,02-00-00,59 ST 2016-08-22 08:00:00  5791829
15              A002,R051,02-00-00,59 ST 2016-08-22 12:00:00  5792007
16              A002,R051,02-00-00,59 ST 2016-08-22 16:00:00  5792315
17              A002,R051,02-00-00,59 ST 2016-08-22 20:00:00  5793152
18              A002,R051,02-00-00,59 ST 2016-08-23 00:00:00  5793399
19              A002,R051,02-00-00,59 ST 2016-08-23 04:00:00  5793422
20              A002,R051,02-00-00,59 ST 2016-08-23 08:00:00  5793475
21              A002,R051,02-00-00,59 ST 2016-08-23 12:00:00  5793656
22              A002,R051,02-00-00,59 ST 2016-08-23 16:00:00  5793961
23              A002,R051,02-00-00,59 ST 2016-08-23 20:00:00  5794827
24              A002,R051,02-00-00,59 ST 2016-08-24 00:00:00  5795047
25              A002,R051,02-00-00,59 ST 2016-08-24 04:00:00  5795068
26              A002,R051,02-00-00,59 ST 2016-08-24 08:00:00  5795107
27              A002,R051,02-00-00,59 ST 2016-08-24 12:00:00  5795291
28              A002,R051,02-00-00,59 ST 2016-08-24 16:00:00  5795619
29              A002,R051,02-00-00,59 ST 2016-08-24 20:00:00  5796445
30              A002,R051,02-00-00,59 ST 2016-08-25 00:00:00  5796665
31              A002,R051,02-00-00,59 ST 2016-08-25 04:00:00  5796672
32              A002,R051,02-00-00,59 ST 2016-08-25 08:00:00  5796706
33              A002,R051,02-00-00,59 ST 2016-08-25 12:00:00  5796863
34              A002,R051,02-00-00,59 ST 2016-08-25 16:00:00  5797068
35              A002,R051,02-00-00,59 ST 2016-08-25 20:00:00  5797735
36              A002,R051,02-00-00,59 ST 2016-08-26 00:00:00  5797976
37              A002,R051,02-00-00,59 ST 2016-08-26 04:00:00  5798002
38              A002,R051,02-00-00,59 ST 2016-08-26 08:00:00  5798027
39              A002,R051,02-00-00,59 ST 2016-08-26 12:00:00  5798179
40              A002,R051,02-00-00,59 ST 2016-08-26 16:00:00  5798549
41              A002,R051,02-00-00,59 ST 2016-08-26 20:00:00  5799243
42              A002,R051,02-00-00,59 ST 2016-08-27 00:00:00  5799442
43              A002,R051,02-00-00,59 ST 2016-08-27 04:00:00  5799463
44              A002,R051,02-00-00,59 ST 2016-08-27 08:00:00  5799492
45              A002,R051,02-00-00,59 ST 2016-08-27 12:00:00  5799610
46              A002,R051,02-00-00,59 ST 2016-08-27 16:00:00  5799833
47              A002,R051,02-00-00,59 ST 2016-08-27 20:00:00  5800121
48              A002,R051,02-00-00,59 ST 2016-08-28 00:00:00  5800252
49              A002,R051,02-00-00,59 ST 2016-08-28 04:00:00  5800281
...                                  ...                 ...      ...
770781  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-09 02:00:00       46
770782  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-09 06:00:00       46
770783  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-09 10:00:00       46
770784  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-09 14:00:00       46
770785  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-09 18:00:00       46
770786  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-09 22:00:00       46
770787  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-10 02:00:00       46
770788  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-10 06:00:00       46
770789  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-10 10:00:00       46
770790  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-10 14:00:00       46
770791  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-10 18:00:00       46
770792  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-10 22:00:00       46
770793  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-11 02:00:00       46
770794  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-11 06:00:00       46
770795  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-11 10:00:00       46
770796  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-11 14:00:00       46
770797  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-11 18:00:00       46
770798  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-11 22:00:00       46
770799  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 02:00:00       46
770800  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 06:00:00       46
770801  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 09:56:19       46
770802  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 10:00:00       46
770803  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 11:57:55       46
770804  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 14:00:00       46
770805  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 18:00:00       46
770806  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-12 22:00:00       46
770807  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-13 02:00:00       46
770808  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-13 06:00:00       46
770809  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-13 10:00:00       46
770810  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-13 14:00:00       46
770811  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-13 18:00:00       46
770812  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-13 22:00:00       47
770813  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-14 02:00:00       47
770814  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-14 06:00:00       47
770815  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-14 10:00:00       47
770816  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-14 14:00:00       47
770817  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-14 18:00:00       47
770818  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-14 22:00:00       47
770819  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-15 02:00:00       47
770820  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-15 06:00:00       47
770821  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-15 10:00:00       47
770822  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-15 14:00:00       47
770823  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-15 18:00:00       47
770824  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-15 22:00:00       47
770825  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-16 02:00:00       47
770826  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-16 06:00:00       47
770827  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-16 10:00:00       47
770828  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-16 14:00:00       47
770829  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-16 18:00:00       47
770830  S102,R165,00-05-01,TOMPKINSVILLE 2016-09-16 22:00:00       47

[770831 rows x 3 columns]

**Exercise 1.3**

These counts are for every n hours. (What is n?) We want total daily entries.  
>> N equals 4.

Now make it that we again have the same keys, but now we have a single value for a single day, which is the total number of passengers that entered through this turnstile on this day.

In [7]:
# Step 1: difference the data from above
month['PERIOD ENTRIES'] = month['ENTRIES'].diff()

month.head(50)

                    LOCATION           DATE/TIME  ENTRIES  PERIOD ENTRIES
0   A002,R051,02-00-00,59 ST 2016-08-20 00:00:00  5790246             NaN
1   A002,R051,02-00-00,59 ST 2016-08-20 04:00:00  5790275            29.0
2   A002,R051,02-00-00,59 ST 2016-08-20 08:00:00  5790284             9.0
3   A002,R051,02-00-00,59 ST 2016-08-20 12:00:00  5790377            93.0
4   A002,R051,02-00-00,59 ST 2016-08-20 16:00:00  5790605           228.0
5   A002,R051,02-00-00,59 ST 2016-08-20 20:00:00  5790926           321.0
6   A002,R051,02-00-00,59 ST 2016-08-21 00:00:00  5791095           169.0
7   A002,R051,02-00-00,59 ST 2016-08-21 04:00:00  5791132            37.0
8   A002,R051,02-00-00,59 ST 2016-08-21 08:00:00  5791141             9.0
9   A002,R051,02-00-00,59 ST 2016-08-21 12:00:00  5791217            76.0
10  A002,R051,02-00-00,59 ST 2016-08-21 16:00:00  5791385           168.0
11  A002,R051,02-00-00,59 ST 2016-08-21 20:00:00  5791648           263.0
12  A002,R051,02-00-00,59 ST 2016-08-22 00:00:00  5791766           118.0
13  A002,R051,02-00-00,59 ST 2016-08-22 04:00:00  5791782            16.0
14  A002,R051,02-00-00,59 ST 2016-08-22 08:00:00  5791829            47.0
15  A002,R051,02-00-00,59 ST 2016-08-22 12:00:00  5792007           178.0
16  A002,R051,02-00-00,59 ST 2016-08-22 16:00:00  5792315           308.0
17  A002,R051,02-00-00,59 ST 2016-08-22 20:00:00  5793152           837.0
18  A002,R051,02-00-00,59 ST 2016-08-23 00:00:00  5793399           247.0
19  A002,R051,02-00-00,59 ST 2016-08-23 04:00:00  5793422            23.0
20  A002,R051,02-00-00,59 ST 2016-08-23 08:00:00  5793475            53.0
21  A002,R051,02-00-00,59 ST 2016-08-23 12:00:00  5793656           181.0
22  A002,R051,02-00-00,59 ST 2016-08-23 16:00:00  5793961           305.0
23  A002,R051,02-00-00,59 ST 2016-08-23 20:00:00  5794827           866.0
24  A002,R051,02-00-00,59 ST 2016-08-24 00:00:00  5795047           220.0
25  A002,R051,02-00-00,59 ST 2016-08-24 04:00:00  5795068            21.0
26  A002,R051,02-00-00,59 ST 2016-08-24 08:00:00  5795107            39.0
27  A002,R051,02-00-00,59 ST 2016-08-24 12:00:00  5795291           184.0
28  A002,R051,02-00-00,59 ST 2016-08-24 16:00:00  5795619           328.0
29  A002,R051,02-00-00,59 ST 2016-08-24 20:00:00  5796445           826.0
30  A002,R051,02-00-00,59 ST 2016-08-25 00:00:00  5796665           220.0
31  A002,R051,02-00-00,59 ST 2016-08-25 04:00:00  5796672             7.0
32  A002,R051,02-00-00,59 ST 2016-08-25 08:00:00  5796706            34.0
33  A002,R051,02-00-00,59 ST 2016-08-25 12:00:00  5796863           157.0
34  A002,R051,02-00-00,59 ST 2016-08-25 16:00:00  5797068           205.0
35  A002,R051,02-00-00,59 ST 2016-08-25 20:00:00  5797735           667.0
36  A002,R051,02-00-00,59 ST 2016-08-26 00:00:00  5797976           241.0
37  A002,R051,02-00-00,59 ST 2016-08-26 04:00:00  5798002            26.0
38  A002,R051,02-00-00,59 ST 2016-08-26 08:00:00  5798027            25.0
39  A002,R051,02-00-00,59 ST 2016-08-26 12:00:00  5798179           152.0
40  A002,R051,02-00-00,59 ST 2016-08-26 16:00:00  5798549           370.0
41  A002,R051,02-00-00,59 ST 2016-08-26 20:00:00  5799243           694.0
42  A002,R051,02-00-00,59 ST 2016-08-27 00:00:00  5799442           199.0
43  A002,R051,02-00-00,59 ST 2016-08-27 04:00:00  5799463            21.0
44  A002,R051,02-00-00,59 ST 2016-08-27 08:00:00  5799492            29.0
45  A002,R051,02-00-00,59 ST 2016-08-27 12:00:00  5799610           118.0
46  A002,R051,02-00-00,59 ST 2016-08-27 16:00:00  5799833           223.0
47  A002,R051,02-00-00,59 ST 2016-08-27 20:00:00  5800121           288.0
48  A002,R051,02-00-00,59 ST 2016-08-28 00:00:00  5800252           131.0
49  A002,R051,02-00-00,59 ST 2016-08-28 04:00:00  5800281            29.0

In [8]:
month.tail(50)

,LOCATION,DATE/TIME,ENTRIES,PERIOD ENTRIES
770781,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 02:00:00,46,0.0
770782,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 06:00:00,46,0.0
770783,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 10:00:00,46,0.0
770784,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 14:00:00,46,0.0
770785,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 18:00:00,46,0.0
770786,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 22:00:00,46,0.0
770787,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 02:00:00,46,0.0
770788,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 06:00:00,46,0.0
770789,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 10:00:00,46,0.0
770790,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 14:00:00,46,0.0
770791,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 18:00:00,46,0.0
770792,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 22:00:00,46,0.0
770793,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 02:00:00,46,0.0
770794,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 06:00:00,46,0.0
770795,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 10:00:00,46,0.0
770796,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 14:00:00,46,0.0
770797,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 18:00:00,46,0.0
770798,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 22:00:00,46,0.0
770799,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 02:00:00,46,0.0
770800,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 06:00:00,46,0.0
770801,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 09:56:19,46,0.0
770802,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 10:00:00,46,0.0
770803,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 11:57:55,46,0.0
770804,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 14:00:00,46,0.0
770805,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 18:00:00,46,0.0
770806,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 22:00:00,46,0.0
770807,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 02:00:00,46,0.0
770808,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 06:00:00,46,0.0
770809,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 10:00:00,46,0.0
770810,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 14:00:00,46,0.0
770811,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 18:00:00,46,0.0
770812,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 22:00:00,47,1.0
770813,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 02:00:00,47,0.0
770814,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 06:00:00,47,0.0
770815,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 10:00:00,47,0.0
770816,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 14:00:00,47,0.0
770817,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 18:00:00,47,0.0
770818,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 22:00:00,47,0.0
770819,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 02:00:00,47,0.0
770820,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 06:00:00,47,0.0
770821,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 10:00:00,47,0.0
770822,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 14:00:00,47,0.0
770823,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 18:00:00,47,0.0
770824,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 22:00:00,47,0.0
770825,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 02:00:00,47,0.0
770826,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 06:00:00,47,0.0
770827,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 10:00:00,47,0.0
770828,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 14:00:00,47,0.0
770829,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 18:00:00,47,0.0
770830,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 22:00:00,47,0.0

In [9]:
# Now shift all the rows up by one so the period totals for one day are all grouped ON that day
month['PERIOD ENTRIES'] = month['PERIOD ENTRIES'].shift(periods = -1)
month.head(100)

                    LOCATION           DATE/TIME  ENTRIES  PERIOD ENTRIES
0   A002,R051,02-00-00,59 ST 2016-08-20 00:00:00  5790246            29.0
1   A002,R051,02-00-00,59 ST 2016-08-20 04:00:00  5790275             9.0
2   A002,R051,02-00-00,59 ST 2016-08-20 08:00:00  5790284            93.0
3   A002,R051,02-00-00,59 ST 2016-08-20 12:00:00  5790377           228.0
4   A002,R051,02-00-00,59 ST 2016-08-20 16:00:00  5790605           321.0
5   A002,R051,02-00-00,59 ST 2016-08-20 20:00:00  5790926           169.0
6   A002,R051,02-00-00,59 ST 2016-08-21 00:00:00  5791095            37.0
7   A002,R051,02-00-00,59 ST 2016-08-21 04:00:00  5791132             9.0
8   A002,R051,02-00-00,59 ST 2016-08-21 08:00:00  5791141            76.0
9   A002,R051,02-00-00,59 ST 2016-08-21 12:00:00  5791217           168.0
10  A002,R051,02-00-00,59 ST 2016-08-21 16:00:00  5791385           263.0
11  A002,R051,02-00-00,59 ST 2016-08-21 20:00:00  5791648           118.0
12  A002,R051,02-00-00,59 ST 2016-08-22 00:00:00  5791766            16.0
13  A002,R051,02-00-00,59 ST 2016-08-22 04:00:00  5791782            47.0
14  A002,R051,02-00-00,59 ST 2016-08-22 08:00:00  5791829           178.0
15  A002,R051,02-00-00,59 ST 2016-08-22 12:00:00  5792007           308.0
16  A002,R051,02-00-00,59 ST 2016-08-22 16:00:00  5792315           837.0
17  A002,R051,02-00-00,59 ST 2016-08-22 20:00:00  5793152           247.0
18  A002,R051,02-00-00,59 ST 2016-08-23 00:00:00  5793399            23.0
19  A002,R051,02-00-00,59 ST 2016-08-23 04:00:00  5793422            53.0
20  A002,R051,02-00-00,59 ST 2016-08-23 08:00:00  5793475           181.0
21  A002,R051,02-00-00,59 ST 2016-08-23 12:00:00  5793656           305.0
22  A002,R051,02-00-00,59 ST 2016-08-23 16:00:00  5793961           866.0
23  A002,R051,02-00-00,59 ST 2016-08-23 20:00:00  5794827           220.0
24  A002,R051,02-00-00,59 ST 2016-08-24 00:00:00  5795047            21.0
25  A002,R051,02-00-00,59 ST 2016-08-24 04:00:00  5795068            39.0
26  A002,R051,02-00-00,59 ST 2016-08-24 08:00:00  5795107           184.0
27  A002,R051,02-00-00,59 ST 2016-08-24 12:00:00  5795291           328.0
28  A002,R051,02-00-00,59 ST 2016-08-24 16:00:00  5795619           826.0
29  A002,R051,02-00-00,59 ST 2016-08-24 20:00:00  5796445           220.0
30  A002,R051,02-00-00,59 ST 2016-08-25 00:00:00  5796665             7.0
31  A002,R051,02-00-00,59 ST 2016-08-25 04:00:00  5796672            34.0
32  A002,R051,02-00-00,59 ST 2016-08-25 08:00:00  5796706           157.0
33  A002,R051,02-00-00,59 ST 2016-08-25 12:00:00  5796863           205.0
34  A002,R051,02-00-00,59 ST 2016-08-25 16:00:00  5797068           667.0
35  A002,R051,02-00-00,59 ST 2016-08-25 20:00:00  5797735           241.0
36  A002,R051,02-00-00,59 ST 2016-08-26 00:00:00  5797976            26.0
37  A002,R051,02-00-00,59 ST 2016-08-26 04:00:00  5798002            25.0
38  A002,R051,02-00-00,59 ST 2016-08-26 08:00:00  5798027           152.0
39  A002,R051,02-00-00,59 ST 2016-08-26 12:00:00  5798179           370.0
40  A002,R051,02-00-00,59 ST 2016-08-26 16:00:00  5798549           694.0
41  A002,R051,02-00-00,59 ST 2016-08-26 20:00:00  5799243           199.0
42  A002,R051,02-00-00,59 ST 2016-08-27 00:00:00  5799442            21.0
43  A002,R051,02-00-00,59 ST 2016-08-27 04:00:00  5799463            29.0
44  A002,R051,02-00-00,59 ST 2016-08-27 08:00:00  5799492           118.0
45  A002,R051,02-00-00,59 ST 2016-08-27 12:00:00  5799610           223.0
46  A002,R051,02-00-00,59 ST 2016-08-27 16:00:00  5799833           288.0
47  A002,R051,02-00-00,59 ST 2016-08-27 20:00:00  5800121           131.0
48  A002,R051,02-00-00,59 ST 2016-08-28 00:00:00  5800252            29.0
49  A002,R051,02-00-00,59 ST 2016-08-28 04:00:00  5800281            14.0
50  A002,R051,02-00-00,59 ST 2016-08-28 08:00:00  5800295            82.0
51  A002,R051,02-00-00,59 ST 2016-08-28 12:00:00  5800377           195.0
52  A002,R051,02-00-00,59 ST 2016-08-28 16:00:00  5800572           226.0
53  A002,R051,02-00-00,59 ST 2016-08-28 20:00:00  5800798           136.0
54  A002,R051,02-00-00,59 ST 2016-08-29 00:00:00  5800934            13.0
55  A002,R051,02-00-00,59 ST 2016-08-29 04:00:00  5800947            49.0
56  A002,R051,02-00-00,59 ST 2016-08-29 08:00:00  5800996           180.0
57  A002,R051,02-00-00,59 ST 2016-08-29 12:00:00  5801176           319.0
58  A002,R051,02-00-00,59 ST 2016-08-29 16:00:00  5801495           841.0
59  A002,R051,02-00-00,59 ST 2016-08-29 20:00:00  5802336           178.0
60  A002,R051,02-00-00,59 ST 2016-08-30 00:00:00  5802514            14.0
61  A002,R051,02-00-00,59 ST 2016-08-30 04:00:00  5802528            47.0
62  A002,R051,02-00-00,59 ST 2016-08-30 08:00:00  5802575           185.0
63  A002,R051,02-00-00,59 ST 2016-08-30 12:00:00  5802760           287.0
64  A002,R051,02-00-00,59 ST 2016-08-30 16:00:00  5803047           828.0
65  A002,R051,02-00-00,59 ST 2016-08-30 20:00:00  5803875           196.0
66  A002,R051,02-00-00,59 ST 2016-08-31 00:00:00  5804071            13.0
67  A002,R051,02-00-00,59 ST 2016-08-31 04:00:00  5804084            45.0
68  A002,R051,02-00-00,59 ST 2016-08-31 08:00:00  5804129           179.0
69  A002,R051,02-00-00,59 ST 2016-08-31 12:00:00  5804308           281.0
70  A002,R051,02-00-00,59 ST 2016-08-31 16:00:00  5804589           794.0
71  A002,R051,02-00-00,59 ST 2016-08-31 20:00:00  5805383           255.0
72  A002,R051,02-00-00,59 ST 2016-09-01 00:00:00  5805638            20.0
73  A002,R051,02-00-00,59 ST 2016-09-01 04:00:00  5805658            51.0
74  A002,R051,02-00-00,59 ST 2016-09-01 08:00:00  5805709           155.0
75  A002,R051,02-00-00,59 ST 2016-09-01 12:00:00  5805864           289.0
76  A002,R051,02-00-00,59 ST 2016-09-01 16:00:00  5806153           837.0
77  A002,R051,02-00-00,59 ST 2016-09-01 20:00:00  5806990           242.0
78  A002,R051,02-00-00,59 ST 2016-09-02 00:00:00  5807232            31.0
79  A002,R051,02-00-00,59 ST 2016-09-02 04:00:00  5807263            46.0
80  A002,R051,02-00-00,59 ST 2016-09-02 08:00:00  5807309           170.0
81  A002,R051,02-00-00,59 ST 2016-09-02 12:00:00  5807479           470.0
82  A002,R051,02-00-00,59 ST 2016-09-02 16:00:00  5807949           667.0
83  A002,R051,02-00-00,59 ST 2016-09-02 20:00:00  5808616           230.0
84  A002,R051,02-00-00,59 ST 2016-09-03 00:00:00  5808846            31.0
85  A002,R051,02-00-00,59 ST 2016-09-03 04:00:00  5808877            23.0
86  A002,R051,02-00-00,59 ST 2016-09-03 08:00:00  5808900            97.0
87  A002,R051,02-00-00,59 ST 2016-09-03 12:00:00  5808997           237.0
88  A002,R051,02-00-00,59 ST 2016-09-03 16:00:00  5809234           288.0
89  A002,R051,02-00-00,59 ST 2016-09-03 20:00:00  5809522           145.0
90  A002,R051,02-00-00,59 ST 2016-09-04 00:00:00  5809667            21.0
91  A002,R051,02-00-00,59 ST 2016-09-04 04:00:00  5809688             6.0
92  A002,R051,02-00-00,59 ST 2016-09-04 08:00:00  5809694            69.0
93  A002,R051,02-00-00,59 ST 2016-09-04 12:00:00  5809763           194.0
94  A002,R051,02-00-00,59 ST 2016-09-04 16:00:00  5809957           231.0
95  A002,R051,02-00-00,59 ST 2016-09-04 20:00:00  5810188           113.0
96  A002,R051,02-00-00,59 ST 2016-09-05 00:00:00  5810301            27.0
97  A002,R051,02-00-00,59 ST 2016-09-05 04:00:00  5810328            10.0
98  A002,R051,02-00-00,59 ST 2016-09-05 08:00:00  5810338            90.0
99  A002,R051,02-00-00,59 ST 2016-09-05 12:00:00  5810428           182.0

In [11]:
# Check how often the values are negative
negatives = month['PERIOD ENTRIES'] < 0
negatives.sum()
# This returns 7861, which is barely 1% of the data.  AND, that includes the ones that should be eliminated
# due to differencing across turnstiles.

7861

In [12]:
# Drop negative values for 'PERIOD ENTRIES' (these reflect changes between turnstiles + turnstile resets)
month = month[month['PERIOD ENTRIES'] >= 0]

# Reindex the data again
month = month.reset_index()
month = month.drop('index', axis = 1)
month

,LOCATION,DATE/TIME,ENTRIES,PERIOD ENTRIES
0,"A002,R051,02-00-00,59 ST",2016-08-20 00:00:00,5790246,29.0
1,"A002,R051,02-00-00,59 ST",2016-08-20 04:00:00,5790275,9.0
2,"A002,R051,02-00-00,59 ST",2016-08-20 08:00:00,5790284,93.0
3,"A002,R051,02-00-00,59 ST",2016-08-20 12:00:00,5790377,228.0
4,"A002,R051,02-00-00,59 ST",2016-08-20 16:00:00,5790605,321.0
5,"A002,R051,02-00-00,59 ST",2016-08-20 20:00:00,5790926,169.0
6,"A002,R051,02-00-00,59 ST",2016-08-21 00:00:00,5791095,37.0
7,"A002,R051,02-00-00,59 ST",2016-08-21 04:00:00,5791132,9.0
8,"A002,R051,02-00-00,59 ST",2016-08-21 08:00:00,5791141,76.0
9,"A002,R051,02-00-00,59 ST",2016-08-21 12:00:00,5791217,168.0
10,"A002,R051,02-00-00,59 ST",2016-08-21 16:00:00,5791385,263.0
11,"A002,R051,02-00-00,59 ST",2016-08-21 20:00:00,5791648,118.0
12,"A002,R051,02-00-00,59 ST",2016-08-22 00:00:00,5791766,16.0
13,"A002,R051,02-00-00,59 ST",2016-08-22 04:00:00,5791782,47.0
14,"A002,R051,02-00-00,59 ST",2016-08-22 08:00:00,5791829,178.0
15,"A002,R051,02-00-00,59 ST",2016-08-22 12:00:00,5792007,308.0
16,"A002,R051,02-00-00,59 ST",2016-08-22 16:00:00,5792315,837.0
17,"A002,R051,02-00-00,59 ST",2016-08-22 20:00:00,5793152,247.0
18,"A002,R051,02-00-00,59 ST",2016-08-23 00:00:00,5793399,23.0
19,"A002,R051,02-00-00,59 ST",2016-08-23 04:00:00,5793422,53.0
20,"A002,R051,02-00-00,59 ST",2016-08-23 08:00:00,5793475,181.0
21,"A002,R051,02-00-00,59 ST",2016-08-23 12:00:00,5793656,305.0
22,"A002,R051,02-00-00,59 ST",2016-08-23 16:00:00,5793961,866.0
23,"A002,R051,02-00-00,59 ST",2016-08-23 20:00:00,5794827,220.0
24,"A002,R051,02-00-00,59 ST",2016-08-24 00:00:00,5795047,21.0
25,"A002,R051,02-00-00,59 ST",2016-08-24 04:00:00,5795068,39.0
26,"A002,R051,02-00-00,59 ST",2016-08-24 08:00:00,5795107,184.0
27,"A002,R051,02-00-00,59 ST",2016-08-24 12:00:00,5795291,328.0
28,"A002,R051,02-00-00,59 ST",2016-08-24 16:00:00,5795619,826.0
29,"A002,R051,02-00-00,59 ST",2016-08-24 20:00:00,5796445,220.0
30,"A002,R051,02-00-00,59 ST",2016-08-25 00:00:00,5796665,7.0
31,"A002,R051,02-00-00,59 ST",2016-08-25 04:00:00,5796672,34.0
32,"A002,R051,02-00-00,59 ST",2016-08-25 08:00:00,5796706,157.0
33,"A002,R051,02-00-00,59 ST",2016-08-25 12:00:00,5796863,205.0
34,"A002,R051,02-00-00,59 ST",2016-08-25 16:00:00,5797068,667.0
35,"A002,R051,02-00-00,59 ST",2016-08-25 20:00:00,5797735,241.0
36,"A002,R051,02-00-00,59 ST",2016-08-26 00:00:00,5797976,26.0
37,"A002,R051,02-00-00,59 ST",2016-08-26 04:00:00,5798002,25.0
38,"A002,R051,02-00-00,59 ST",2016-08-26 08:00:00,5798027,152.0
39,"A002,R051,02-00-00,59 ST",2016-08-26 12:00:00,5798179,370.0
40,"A002,R051,02-00-00,59 ST",2016-08-26 16:00:00,5798549,694.0
41,"A002,R051,02-00-00,59 ST",2016-08-26 20:00:00,5799243,199.0
42,"A002,R051,02-00-00,59 ST",2016-08-27 00:00:00,5799442,21.0
43,"A002,R051,02-00-00,59 ST",2016-08-27 04:00:00,5799463,29.0
44,"A002,R051,02-00-00,59 ST",2016-08-27 08:00:00,5799492,118.0
45,"A002,R051,02-00-00,59 ST",2016-08-27 12:00:00,5799610,223.0
46,"A002,R051,02-00-00,59 ST",2016-08-27 16:00:00,5799833,288.0
47,"A002,R051,02-00-00,59 ST",2016-08-27 20:00:00,5800121,131.0
48,"A002,R051,02-00-00,59 ST",2016-08-28 00:00:00,5800252,29.0
49,"A002,R051,02-00-00,59 ST",2016-08-28 04:00:00,5800281,14.0
...,...,...,...,...
762919,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-08 22:00:00,46,0.0
762920,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 02:00:00,46,0.0
762921,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 06:00:00,46,0.0
762922,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 10:00:00,46,0.0
762923,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 14:00:00,46,0.0
762924,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 18:00:00,46,0.0
762925,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-09 22:00:00,46,0.0
762926,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 02:00:00,46,0.0
762927,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 06:00:00,46,0.0
762928,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 10:00:00,46,0.0
762929,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 14:00:00,46,0.0
762930,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 18:00:00,46,0.0
762931,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-10 22:00:00,46,0.0
762932,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 02:00:00,46,0.0
762933,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 06:00:00,46,0.0
762934,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 10:00:00,46,0.0
762935,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 14:00:00,46,0.0
762936,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 18:00:00,46,0.0
762937,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-11 22:00:00,46,0.0
762938,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 02:00:00,46,0.0
762939,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 06:00:00,46,0.0
762940,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 09:56:19,46,0.0
762941,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 10:00:00,46,0.0
762942,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 11:57:55,46,0.0
762943,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 14:00:00,46,0.0
762944,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 18:00:00,46,0.0
762945,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-12 22:00:00,46,0.0
762946,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 02:00:00,46,0.0
762947,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 06:00:00,46,0.0
762948,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 10:00:00,46,0.0
762949,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 14:00:00,46,0.0
762950,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 18:00:00,46,1.0
762951,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-13 22:00:00,47,0.0
762952,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 02:00:00,47,0.0
762953,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 06:00:00,47,0.0
762954,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 10:00:00,47,0.0
762955,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 14:00:00,47,0.0
762956,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 18:00:00,47,0.0
762957,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-14 22:00:00,47,0.0
762958,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 02:00:00,47,0.0
762959,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 06:00:00,47,0.0
762960,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 10:00:00,47,0.0
762961,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 14:00:00,47,0.0
762962,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 18:00:00,47,0.0
762963,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-15 22:00:00,47,0.0
762964,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 02:00:00,47,0.0
762965,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 06:00:00,47,0.0
762966,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 10:00:00,47,0.0
762967,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 14:00:00,47,0.0
762968,"S102,R165,00-05-01,TOMPKINSVILLE",2016-09-16 18:00:00,47,0.0

In [ ]:
# COMPLETE TO HERE

In [ ]:


#The below didn't work for grouping, not sure why
grouped = month.groupby([month['DATE/TIME'].dt.date, month['LOCATION']])
grouped.head(50)

In [ ]:


#Create a new dataframe to store the results of summing the groups
entries_by_day  = month.groupby([month['DATE/TIME'].dt.date, month['LOCATION']]).sum()
#[add .reset_index() to turn this new thing into a dataframe again (doing an operation on it turns it not into a dataframe anymore)]

#Here the index = the date.  Do I want that?

# DOESN'T WORK -- ENTRIES CAN'T JUST BE SUMMED -- I Groupby'd before I got entries in correct time amounts
# Instead: get rid of all entries that aren't hours 00:00:00 or 01:00:00
#Instead create a new dataframe to store the results of keeping just the first entry for each day for each turnstile
#Get unique values for month['DATE/TIME'].dt.date -- verify I just need the above 2


entries_by_day.head(20)